print("Mehal Rashid")
print("18B-063-CS(A)")
print("Assignment #1")
print("Exercise 3.17")

print("\n\neval('2 * 3 + 1')           =",eval('2 * 3 + 1'))
print("\neval('hello')                  = This will print an error because there are no calculations in eval('hello')")
print("\neval,('hello' + ' ' + 'world!')=",eval("'hello' + ' ' + 'world!'"))
print("\neval of ASCII.count(I) will give =",eval("'ASCII'.count('I')"))
print("\neval('x = 5')                  =This will print an error because eval is not an assignment operator eval('x = 5')")
